// <auto-generated />
using DevIncGraph.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DevIncGraph.Migrations
{
    [DbContext(typeof(DevIncGraphContext))]
    [Migration("20190507221404_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DevIncGraph.Models.Point", b =>
                {
                    b.Property<int>("PointId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ChartId");

                    b.Property<int>("PointX");

                    b.Property<int>("PointY");

                    b.Property<int?>("UserDataId");

                    b.HasKey("PointId");

                    b.HasIndex("UserDataId");

                    b.ToTable("ContextPoints");
                });

            modelBuilder.Entity("DevIncGraph.Models.UserData", b =>
                {
                    b.Property<int>("UserDataId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("A");

                    b.Property<int>("B");

                    b.Property<int>("C");

                    b.Property<int>("RangeFrom");

                    b.Property<int>("RangeTo");

                    b.Property<float>("Step");

                    b.HasKey("UserDataId");

                    b.ToTable("ContextUserDatas");
                });

            modelBuilder.Entity("DevIncGraph.Models.Point", b =>
                {
                    b.HasOne("DevIncGraph.Models.UserData", "UserData")
                        .WithMany("Points")
                        .HasForeignKey("UserDataId");
                });
#pragma warning restore 612, 618
        }
    }
}
